<?php

/**
 * @file
 * Contains hooks and functions for lazy image module.
 */

use Drupal\lazy_image\Helper;

/**
 * Implements hook_theme().
 */
function lazy_image_theme() {
  return [
    'lazy_image_wrapper' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Implements hook_theme_registry_alter().
 *
 * Adds 'placeholder' variable to lazy image theme hooks.
 */
function lazy_image_theme_registry_alter(&$theme_registry) {
  $theme_registry['responsive_image_formatter__lazy']['variables']['lazy_placeholder_style'] = '';
  $theme_registry['responsive_image__lazy']['variables']['lazy_placeholder_style'] = '';
  $theme_registry['image_formatter__lazy']['variables']['lazy_placeholder_style'] = '';
  $theme_registry['image_style__lazy']['variables']['lazy_placeholder_style'] = '';
  $theme_registry['image__lazy']['variables']['lazy_placeholder_style'] = '';

  // Deprecated placeholder image inclusion technique.
  $theme_registry['responsive_image_formatter__lazy']['variables']['lazy_placeholder'] = '';
  $theme_registry['responsive_image__lazy']['variables']['lazy_placeholder'] = '';
  $theme_registry['image_formatter__lazy']['variables']['lazy_placeholder'] = '';
  $theme_registry['image_style__lazy']['variables']['lazy_placeholder'] = '';
  $theme_registry['image__lazy']['variables']['lazy_placeholder'] = '';
}

/**
 * Prepares variables for lazy image wrapper templates.
 *
 * Default template: lazy-image-wrappe.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the image.
 *     Properties used: #children, #no_js_fallback.
 */
function template_preprocess_lazy_image_wrapper(array &$variables) {
  $element = $variables['element'];

  // Map variables.
  $variables['image'] = $element['#children'];
  $variables['no_js_fallback'] = $element['#no_js_fallback'];
}

/**
 * Implements hook_preprocess_HOOK() for image-formatter--lazy.html.twig.
 */
function lazy_image_preprocess_image_formatter__lazy(&$variables) {
  $variables['image']['#theme'] .= '__lazy';
  $variables['image']['#lazy_placeholder_style'] = $variables['lazy_placeholder_style'];

  // Deprecated placeholder image inclusion technique.
  $variables['image']['#lazy_placeholder'] = $variables['lazy_placeholder'];
}

/**
 * Implements hook_preprocess_HOOK() for image-style--lazy.html.twig.
 */
function lazy_image_preprocess_image_style__lazy(&$variables) {
  $variables['image']['#theme'] .= '__lazy';
  $variables['image']['#lazy_placeholder_style'] = $variables['lazy_placeholder_style'];

  // Deprecated placeholder image inclusion technique.
  $variables['image']['#lazy_placeholder'] = $variables['lazy_placeholder'];
}

/**
 * Implements hook_preprocess_HOOK() for image--lazy.html.twig.
 */
function lazy_image_preprocess_image__lazy(&$variables) {
  foreach (['src', 'srcset'] as $attribute_name) {
    if (isset($variables['attributes'][$attribute_name])) {
      $variables['attributes']["data-$attribute_name"] = $variables['attributes'][$attribute_name];
      unset($variables['attributes'][$attribute_name]);
    }
  }

  // Add JS lazy-loading library.
  $variables['attributes']['class'][] = Helper::CSS_CLASS;
  $variables['#attached']['library'][] = 'lazy_image/lazysizes';

  // Set URL of placeholder image from the provided image style to the image
  // tag if provided.
  $placeholder_style = \Drupal::entityTypeManager()
    ->getStorage('image_style')
    ->load($variables['lazy_placeholder_style']);

  if ($placeholder_style) {
    $variables['attributes']['src'] = $placeholder_style->buildUrl($variables['uri']);
    \Drupal::service('renderer')->addCacheableDependency($variables, $placeholder_style);
  }
  // Deprecated placeholder image inclusion technique.
  elseif ($variables['lazy_placeholder']) {
    $variables['attributes']['src'] = $variables['lazy_placeholder'];
  }
}

/**
 * Implements hook_preprocess_HOOK() for responsive-image--lazy.html.twig.
 */
function lazy_image_preprocess_responsive_image__lazy(&$variables) {
  $img = $variables['img_element'];
  $image_style_storage = \Drupal::entityTypeManager()->getStorage('image_style');

  // If outputting image tag only:
  if ($variables['output_image_tag']) {
    $variables['img_element']['#attributes']['data-srcset'] = $variables['sources'][0]['srcset'];
    unset($variables['img_element']['#attributes']['srcset']);
  }
  else {
    // Convert srcset attributes on source tags.
    foreach ($variables['sources'] as $value) {
      $value->setAttribute('data-srcset', $value['srcset']);
      $value->removeAttribute('srcset');
    }
  }

  $fallback_style = \Drupal::entityTypeManager()
    ->getStorage('responsive_image_style')
    ->load($variables['responsive_image_style_id'])
    ->getFallbackImageStyle();

  // Use fallback image style's dimensions for image dimension attributes, to
  // mitigate some content jumping.
  $variables['img_element']['#attributes']['height'] = $variables['height'];
  $variables['img_element']['#attributes']['width'] = $variables['width'];
  $image_style_storage
    ->load($fallback_style)
    ->transformDimensions($variables['img_element']['#attributes'], $variables['uri']);

  // Add JS library.
  $variables['img_element']['#attributes']['class'][] = Helper::CSS_CLASS;
  $variables['#attached']['library'][] = 'lazy_image/lazysizes';

  // Move original URI to data- attribute.
  $variables['img_element']['#attributes']['data-src'] = $img['#uri'];
  $variables['img_element']['#uri'] = '';

  // Set URL of placeholder image from the provided image style to the image
  // tag if provided.
  $placeholder_style = $image_style_storage->load($variables['lazy_placeholder_style']);
  if ($placeholder_style) {
    $variables['img_element']['#uri'] = $placeholder_style->buildUrl($variables['uri']);
    \Drupal::service('renderer')->addCacheableDependency($variables, $placeholder_style);
  }
  // Deprecated placeholder image inclusion technique.
  elseif ($variables['lazy_placeholder']) {
    $variables['attributes']['src'] = $variables['lazy_placeholder'];
  }
}

/**
 * Implements hook_preprocess_HOOK() for responsive-image-formatter--lazy.html.twig.
 */
function lazy_image_preprocess_responsive_image_formatter__lazy(&$variables) {
  if (isset($variables['responsive_image']['#type'])) {
    unset($variables['responsive_image']['#type']);
    $variables['responsive_image']['#theme'] = 'responsive_image__lazy';
  }
  else {
    $variables['responsive_image']['#theme'] .= '__lazy';
  }

  $variables['responsive_image']['#lazy_placeholder_style'] = $variables['lazy_placeholder_style'];

  // Deprecated placeholder image inclusion technique.
  $variables['responsive_image']['#lazy_placeholder'] = $variables['lazy_placeholder'];
}

/**
 * Implements hook_page_bottom().
 *
 * Adds noscript CSS to hide lazy images.
 */
function lazy_image_page_bottom(array &$page_bottom) {
  $page_bottom['lazy_image_noscript'] = [
    '#type' => 'html_tag',
    '#tag' => 'style',
    '#value' => 'img[data-src],img[data-srcset]{display:none}',
    '#noscript' => TRUE,
  ];
}
